### ISSUE TITLE
Adding additional ODI and packet drivers wanted?

### ISSUE THREAD

**Issue by creopard** [gammy/dos_net_ne2000#1]
Hi @gammy, I was wondering if you would like to add additional ODI, packet drivers and config programs for common 3Com network cards (like 3C509 and 3C90x) to this nice repository?

If so, I can provide the necessary files.

**Comment by gammy** [comment]
Hi! 
My apologise for the delay; I saw it a few days ago but haven't had time to respond.
I'm glad you've found use of this dusty repo!

That sounds neat, and although I don't have a problem with it, the name of this repo (and its contents) is very targeted towards ne2000. I wonder if it wouldn't be better for you to clone the repo with a more generic name (like `dos_net_common` or similar) and add your stuff to that? I could then point others to your repo in case they need it (and/or merge other improvements you might make into this repo).

Let me know what you think, and have a great weekend!

**Comment by creopard** [comment]
I see, so let's keep this repository just NE2000 related ;)

**Comment by gammy** [comment]
..but if you do fork it into your own thing, please let me know so that I can link to your project!

**Comment by creopard** [comment]
@gammy I've started to "update" the repository (3com components will follow shortly).
Would you also like to have the updated mTCP components in your repository, see https://github.com/gammy/dos_net_ne2000/compare/master...creopard:dos_net_ne2000_3com:master ?
